version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.2
    steps:
      - checkout
      - run:
          name: Restore solution
          command: dotnet restore src/
      - run:
          name: Build solution
command: dotnet build src/